services:
  # ollama:
  #   image: ollama/ollama
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama-data:/root/.ollama
  #   restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: local-llm-api
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
      - ./files:/app/files
      - faiss-data:/app/faiss_index
    # depends_on:
    #   - ollama
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: local-llm-ui
    command: streamlit run main.py --server.port=8501 --server.address=0.0.0.0 --server.runOnSave true
    ports:
      - "8501:8501"
    volumes:
      - ./ui:/app
    depends_on:
      - api

volumes:
  ollama-data:
  faiss-data:
