FROM python:3.10-slim

WORKDIR /app

COPY requirements.ui.txt .
RUN pip install --no-cache-dir -r requirements.ui.txt

COPY ui/ .

CMD ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]
