services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped

  chroma:
    image: ghcr.io/chroma-core/chroma:1.0.15
    container_name: chromadb
    ports:
      - "8001:8000"
    volumes:
      - chroma-data:/chroma/.chroma
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: local-llm-api
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
      - ./files:/app/files
    depends_on:
      - ollama
      - chroma
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: local-llm-ui
    ports:
      - "8501:8501"
    depends_on:
      - api

volumes:
  ollama-data:
  chroma-data:
